[phases.setup]
nixPkgs = [
  "python311",
  "libglvnd",
  "glib",
  "mesa",
  "xorg.libxcb",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libSM",
  "xorg.libICE"
]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
